### ISSUE TITLE
users may not see the menu

### ISSUE THREAD

**Issue by pgiraud** [state-hiu/osmgeoweek-2014#11]
When I first loaded the page from osmgeoweek, I didn't know where to click. It took me time to figure out that the text in the top bar was actually menu items.
It would be nice to make it more clear (item background or more space between items).

![screenshot from 2014-10-24 09 36 32](https://cloud.githubusercontent.com/assets/319774/4766473/108b87a4-5b51-11e4-9f6b-8e5731537076.png)

**Comment by pgiraud** [comment]
![screenshot from 2014-10-24 09 44 19](https://cloud.githubusercontent.com/assets/319774/4766509/95084d96-5b51-11e4-90da-78e2b0fb97d7.png)

**Comment by mikelmaron** [comment]
Has this change improved this @pgiraud ? Enough space, or more?
https://github.com/mikelmaron/osmgeoweek/commit/3c1d85a4a60cccea14437ae539045625fdc04250

**Comment by pgiraud** [comment]
Looks better.
