### ISSUE TITLE
maptime pdx

### ISSUE THREAD

**Issue by mikelmaron** [state-hiu/osmgeoweek-2014#35]
https://docs.google.com/spreadsheets/d/1wq3b0Y7v8uV-Tc5Bbn6XvQ0A2uLYY_idgM5WuCzEG_Y/notify/show?rev=15&fromRev=15&s=AM5m-fjSxExYAPiOvZ8fjWUe14RhS4HfAg

**Comment by melany32** [comment]
MIkel,

I will get these entered in today!

Thanks,

Melany

**Comment by mikelmaron** [comment]
Actually I've been entering them as I get them, so don't worry about it
- Mikel Maron \* +14152835207 @mikel s:mikelmaron

**Comment by melany32** [comment]
Mikel,

I want to sincerely apologize for not being more helpful.  I know you are
extremely busy and I had every intention of doing a more quality job on
this project.  I realize your efforts to fix my mistakes probably took more
time than if you just entered the events yourself.

Please accept my apology and know that I meant well.  I am presenting my
Master's Thesis in a few weeks and it has been a struggle to balance my
work.

Kind Regards,

Melany
